name: Test and Deploy Static Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            STORAGE_ACCOUNT_NAME="sthastaticwebtest"
            SOURCE_DIRECTORY="webfiles"
            echo "Uploading files from $SOURCE_DIRECTORY to $STORAGE_ACCOUNT_NAME/\$web"
            az storage blob upload-batch \
              --overwrite \
              --account-name $STORAGE_ACCOUNT_NAME \
              --destination '$web/stugan' \
              --source $SOURCE_DIRECTORY \
              --auth-mode login
            echo "Deployment to Azure Storage completed successfully!"

      - name: Azure Logout
        run: |
          az logout
